---
title: "P8105 HW5 jam2530"
author: "Jenna Mohammed"
date: '2023-11-12'
output: github_document
---


```{r warning=FALSE, message=FALSE}
library(tidyverse)
library(rvest)
library(purrr)
library(dplyr)
library(ggplot2)
```

# Problem 2 

Creating a tidy dataframe using list

```{r}
# listing all files using list.files

file_names <- list.files(path="./hw5_data./data", pattern="\\.csv$", all.files=FALSE, full.names=TRUE)

```

```{r}

# create function to read files

all_data <- map_df(file_names, ~ {read.csv(.x)

})

```
 
```{r}
# cleaning and tidying data 

cleaned_df <- all_data |>
  janitor::clean_names() |>
  mutate(subject_ID = as.integer(str_extract(file_names, "[0-9][0-9]"))) |>
  mutate(file_names = ifelse(str_detect(file_names, "con") == TRUE, "Control", "Experiment"))
   
```

Making a Spaghetti Plot 

```{r}
cleaned_df_new = 
 cleaned_df|>
  pivot_longer(week_1:week_8,
               names_to = "week",
               values_to = "outcome",
               names_prefix = "week_"
               ) |>
  mutate(week = as.numeric(week))

cleaned_df_new |>
  ggplot(aes(x = week, y = outcome,
             group = subject_ID, color = file_names)) +
  geom_path() +
  facet_grid(~file_names)
  
```

# Problem 3 

Setting design elements 

```{r}

set.seed(12345)

n <- 30

sigma <- 5

mu <- 0:6

alpha <- 0.05

dataset_total <- 5000

iteration = 1:5000

```

Creating function for hypothesis testing 

```{r}

t_test_sim = function(n, mu, sigma) {
  test = rnorm(n = n, mean = mu, sd = sigma)
  t_test_results = t.test(test)
  t_test_results|>
    broom::tidy()
  
  return(t_test_results)
  
}

 sim_results = expand.grid(sample_size = n, true_mean = mu, iteration = 1:5000) |>
   mutate(
    estimate_df = map2(.x = sample_size, .y = true_mean, ~ sim_t(n = .x, mu = .y))) |>
  unnest(estimate_df)
 
 
 

#sim_results_df = 
#  expand_grid(
#    sample_size = 30,
#    true_mean = c(1, 2, 3, 4, 5, 6),
#    iteration = 1:5000)
  
#  sim_results = expand.grid(
#    simulation = map(mu = 0, iteration = 1:5000, ~ t.test(rnorm(n, mu,    #sigma))),
 #   reject = case_when(
#      alpha < 0.05 ~ "reject",
#      alpha >= 0.05 ~ "fail_to_reject")
#    )
  
  
```

```{r}


power_df <- sim_results |>
  group_by(true_mean) |>
  mutate(reject_null = p.value < 0.05) |>
  summarize(power = mean(reject_null)) |>
  ggplot(aes( x = true_mean, y = power )) +
  geom_point()
```

Questions for TA

- For problem 2, my spaghetti plot doesn't look right(i think i messed up a variable)
- for problem 3, when i try to make the dataframe it doesn't look right